// <auto-generated />
namespace AnimeMusic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Animeandgenretable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Animeandgenretable));
        
        string IMigrationMetadata.Id
        {
            get { return "202307301729241_Anime-and-genre-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
